[package]
name = "rsblog"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-lab = "0.21"
actix-files = "0.6"

tera = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
env_logger = "0.11"
log = "0.4"
thiserror = "1"
include_dir = "0.7"
mime_guess = "2"
base64 = "0.21"
tempfile = "3"
dotenvy = "0.15"
mongodb = "3"
futures = "0.3"

utoipa = { version = "5", features = ["actix_extras"] }
utoipa-swagger-ui = { version = "8", features = ["actix-web"] }
utoipa-redoc = { version = "5", features = ["actix-web"] }
utoipa-rapidoc = { version = "5", features = ["actix-web"] }
utoipa-scalar = { version = "0.2", features = ["actix-web"] }
